version: '3.7'

services:
    nginx:
        image: nginx:stable-alpine
        ports: 
            - 80:80
        volumes:
            - ./.docker_volumes/nginx/nginx.default.conf:/etc/nginx/conf.d/default.conf
    
    postgres:
        image: postgres:11-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: witcher
        volumes:
            - ./.docker_volumes/pgdata:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        ports: 
            - 5432:5432
        

    
    django:
        build:
            context: django
            dockerfile: dockerfile
        volumes:
            - ./django:/app
        depends_on: 
            - postgres
        ports:
            - 8000:8000
    
    django-green:
        image: "ha-django:${NEW_TAG}"
        entrypoint: "gunicorn --bind 0.0.0.0:8000 --workers 3 --timeout 300 witcher.wsgi:application --log-level=WARN --max-requests=1000"
    django-blue:
        image: "ha-django:${CUR_TAG}"
        entrypoint: "gunicorn --bind 0.0.0.0:8000 --workers 3 --timeout 300 witcher.wsgi:application --log-level=WARN --max-requests=1000"
